name: Neovim

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Tests (Neovim ${{ matrix.version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - v0.10.4
          - stable
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.version }}
      - name: Run tests
        run: make test
